server:
  port: 8080
spring:
  datasource:
    username: root
    password: rs
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.130:3307/test?useUnicode=true&characterEncoding=UTF-8